services:
  samba:
    image: "dperson/samba"
    ports:
      - "139:139"
      - "445:445"
    command:
      - -p
      - -u
      - "example1;badpass"
      - -u
      - "example2;badpass"
      - -s
      - "public;/share;no;no;yes;all;none;example1;public"
      - -s
      - "private;/share-2;no;no;no;all;none;none;private"
    volumes:
      - ./tmp/share:/share
      - ./tmp/share-2:/share-2
